Add Streamis 0.3.0
WeBankFinTech/Streamis pull request #93
Opened 2023-08-07 07:22 UTC by Alexkun

### What is the purpose of the change
Add Streamis 0.3.0, including changes from 0.2.0 to 0.3.0

### Brief change log
(for example:)
- Add support for checkpoint of flink.
- Add support for detach manage mode, etc.

### Verifying this change
(Please pick either of the following options)  
This change is a trivial rework / code cleanup without any test coverage.  
(or)  
This change is already covered by existing tests, such as (please describe tests).  
(or)  
This change added tests and can be verified as follows:  
(example:)  
- Added tests for creating and execute the Streamis jobs and verify the availability of different Streamis Job, such as flinkSQL, Jar.

### Does this pull request potentially affect one of the following parts:
- Dependencies (does it add or upgrade a dependency): (yes / no)
- Anything that affects deployment: (yes / no / don't know)
- The Core framework, i.e., JobManager, Server.: (yes / no)

### Documentation
- Does this pull request introduce a new feature? (yes / no)
- If yes, how is the feature documented? (not applicable / docs / JavaDocs / not documented)

2023-08-11 02:51 UTC, wushengyeyouya reviewed
Cantains lots of 0.2.5, 0.2.5-webank and 0.3.1, 0.3.1-webank, please update it.

2023-08-11 02:51 UTC, wushengyeyouya commented on README-ZH.md
> +&nbsp; &nbsp; &nbsp; &nbsp;更多功能，请参考：[Streamis 用户手册](docs/zh_CN/0.2.5-webank/使用文档/Streamis用户手册.md)。
Should change the branch name.

2023-08-11 02:51 UTC, wushengyeyouya commented on README-ZH.md
> +&nbsp; &nbsp; &nbsp; &nbsp;请参考 [Streamis 安装部署文档](docs/zh_CN/0.2.5-webank/Streamis安装文档.md) ，用于安装部署 Streamis 及其依赖环境。
Should change the branch name.

2023-08-11 02:51 UTC, wushengyeyouya commented on README-ZH.md
> +&nbsp; &nbsp; &nbsp; &nbsp;请到 [用户使用文档](docs/zh_CN/0.2.5-webank/使用文档/Streamis用户手册.md) ，了解如何快速使用 Streamis。
Should change the branch name.

2023-08-11 02:51 UTC, wushengyeyouya commented on README.md
> +please refer to [Streamis Installation and Deployment Document](docs/en_US/0.2.5-webank/StreamisDeployment.md) for installing and deploying Streamis.
Should change the branch name.

2023-08-11 02:51 UTC, wushengyeyouya commented on bin/upgrade.sh
> +# Use to upgrade from 0.1.0 to 0.2.5-webank
Should change the branch name.

2023-08-11 13:26 UTC, Alexkun commented on README-ZH.md
> +&nbsp; &nbsp; &nbsp; &nbsp;请到 [用户使用文档](docs/zh_CN/0.2.5-webank/使用文档/Streamis用户手册.md) ，了解如何快速使用 Streamis。
changed file location

2023-08-11 13:28 UTC, Alexkun commented on README.md
> +please refer to [Streamis Installation and Deployment Document](docs/en_US/0.2.5-webank/StreamisDeployment.md) for installing and deploying Streamis.
Updated.

2023-08-11 13:31 UTC, Alexkun commented on bin/upgrade.sh
> +# Use to upgrade from 0.1.0 to 0.2.5-webank
This script should not change.

2023-08-16 02:55 UTC, wushengyeyouya requested changes

2023-08-16 02:55 UTC, wushengyeyouya commented on README.md
> +please refer to [Streamis Installation and Deployment Document](docs/en_US/0.3.0-webank/StreamisDeployment.md) for installing and deploying Streamis.
Please modify it.

2023-08-16 02:55 UTC, wushengyeyouya commented on bin/upgrade025.sh
> +# Use to upgrade from 0.1.0 to 0.2.5-webank
Please modify it.

2023-08-16 02:55 UTC, wushengyeyouya commented on bin/upgrade025.sh
> +interact_echo "Are you sure the current version of Streamis is 0.2.x < 0.2.5 and need to upgrade to 0.2.5 ?"
Please modify it.

2023-08-16 02:55 UTC, wushengyeyouya commented on docs/en_US/0.2.5/StreamisDeployment.md
> +Streamis0.2.5-webank provides the Streamis-JobManager component, the role of the component is <br>
Please modify it.

2023-08-16 03:55 UTC, Alexkun reviewed
updated

2023-08-16 03:55 UTC, Alexkun commented on README.md
> +please refer to [Streamis Installation and Deployment Document](docs/en_US/0.3.0-webank/StreamisDeployment.md) for installing and deploying Streamis.
done

2023-08-16 03:55 UTC, Alexkun commented on bin/upgrade025.sh
> +# Use to upgrade from 0.1.0 to 0.2.5-webank
done

2023-08-16 03:55 UTC, Alexkun commented on bin/upgrade025.sh
> +interact_echo "Are you sure the current version of Streamis is 0.2.x < 0.2.5 and need to upgrade to 0.2.5 ?"
done

2023-08-16 03:55 UTC, Alexkun commented on docs/en_US/0.2.5/StreamisDeployment.md
> +Streamis0.2.5-webank provides the Streamis-JobManager component, the role of the component is <br>
done

2023-08-16 09:54 UTC, wushengyeyouya requested changes

2023-08-16 09:54 UTC, wushengyeyouya commented on docs/en_US/0.2.5/StreamisDeployment.md
> +Streamis0.2.5 provides the Streamis-JobManager component, the role of the component is <br>
Please modify it.

2023-08-16 09:54 UTC, wushengyeyouya commented on docs/en_US/0.2.5/StreamisDeployment.md
> +If you want to run streamis0.2.5 normally, you also need to install the linkis Flink engine. Please refer to: [linkis Flink engine installation document](https://linkis.apache.org/zh-CN/docs/1.1.2/en
Please modify it.

2023-08-16 14:34 UTC, Alexkun commented on docs/en_US/0.2.5/StreamisDeployment.md
> +Streamis0.2.5 provides the Streamis-JobManager component, the role of the component is <br>
done

2023-08-16 14:34 UTC, Alexkun commented on docs/en_US/0.2.5/StreamisDeployment.md
> +If you want to run streamis0.2.5 normally, you also need to install the linkis Flink engine. Please refer to: [linkis Flink engine installation document](https://linkis.apache.org/zh-CN/docs/1.1.2/en
done

2023-08-17 02:40 UTC, wushengyeyouya approved these changes
LGTM.

2023-08-17 02:40 UTC, merged